# This workflow will do a clean install of node dependencies, build the source code and run tests across different versions of node
# For more information see: https://help.github.com/actions/language-and-framework-guides/using-nodejs-with-github-actions

name: 中青自动阅读

on:
  workflow_dispatch:
  schedule:
     - cron: '*/15 1-12/2 * * *'
  watch:
    types: started
jobs:
  build:
    runs-on: ubuntu-latest
    if: github.event.repository.owner.id == github.event.sender.id
    env:
      YOUTH_READ: ${{ secrets.YOUTH_READ }}
      YOUTH_READ2: ${{ secrets.YOUTH_READ2 }}
      YOUTH_READ3: ${{ secrets.YOUTH_READ3 }}
      YOUTH_READ4: ${{ secrets.YOUTH_READ4 }}
      YOUTH_READ5: ${{ secrets.YOUTH_READ5 }}
      YOUTH_READ6: ${{ secrets.YOUTH_READ6 }}
      YOUTH_READ7: ${{ secrets.YOUTH_READ7 }}
      YOUTH_READ8: ${{ secrets.YOUTH_READ8 }}
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Use Node.js 12.x
        uses: actions/setup-node@v1
        with:
          node-version: 12.x
      - name: npm install
        run: |
          npm install
          
      - name: '运行 【中青看点自动阅读一】'
        if: env.YOUTH_READ
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ }}
          YOUTH_TIME: ${{ secrets.YOUTH_TIME }}

      - name: '运行 【中青看点自动阅读二】'
        if: env.YOUTH_READ2
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ2 }}
          YOUTH_TIME: ${{ secrets.YOUTH_TIME2 }}
          
      - name: '运行 【中青看点自动阅读三】'
        if: env.YOUTH_READ3
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ3 }}
          YOUTH_TIME: ${{ secrets.YOUTH_TIME3 }}
          
      - name: '运行 【中青看点自动阅读四】'
        if: env.YOUTH_READ4
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ4 }}
          YOUTH_TIME: ${{ secrets.YOUTH_TIME4 }}
          
      - name: '运行 【中青看点自动阅读五】'
        if: env.YOUTH_READ5
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ5 }}
          YOUTH_TIME: ${{ secrets.YOUTH_TIME5 }}

      - name: '运行 【中青看点自动阅读六】'
        if: env.YOUTH_READ6
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ6 }}
          YOUTH_TIME: ${{ secrets.YOUTH_TIME6 }}

      - name: '运行 【中青看点自动阅读七】'
        if: env.YOUTH_READ7
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ7 }}
          YOUTH_TIME: ${{ secrets.YOUTH_TIME7 }}

      - name: '运行 【中青看点自动阅读八】'
        if: env.YOUTH_READ8
        run: |
          node Task/Youth_Read.js
        env:
          YOUTH_READ: ${{ secrets.YOUTH_READ8 }}
          YOUTH_TIME: ${{ secrets.YOUTH_TIME8 }}
